### ISSUE TITLE
Correctness issue with keyed virtual nodes

### ISSUE THREAD

**Issue by CRogers** [Matt-Esch/virtual-dom#191]
Minimal working example: http://jsfiddle.net/CARogers/o1m76ek8/2/

In the above example there are 3 states (see `gridsOfNodesToRender`) - a 5x2 grid, followed by a 5x3 grid then a 5x2 grid. Each virtual node is keyed with a unique key for it's position in the grid (the key is also the text of each square). At the end we should be left with a 5x2 grid, but it is diffed or patched wrong so there is at least one node in the wrong place (see `2-4`):

Frame 1 - 5x2 | Frame 2 - 5x3 | Frame 3 - 5x2
--------- | ------------- | ------------
![screen shot 2015-02-18 at 17 25 07](https://cloud.githubusercontent.com/assets/397795/6252556/27d11674-b793-11e4-9248-a13257eae37d.png) | ![screen shot 2015-02-18 at 17 25 17](https://cloud.githubusercontent.com/assets/397795/6252564/3196e5f8-b793-11e4-8336-140e9899db42.png) | ![wrongly positioned](https://cloud.githubusercontent.com/assets/397795/6252481/a2d59288-b792-11e4-971c-42aa1cca027a.png)

This is a pared down example of a real problem I encountered in production code. I made an example closer to the actual problem here: http://jsfiddle.net/CARogers/tsjLprv0/

You can drag the squares around and they'll hide if they go off the edge of the grey square. Example video: https://www.dropbox.com/s/bnxf995zpjqit33/virtualDom.mov?dl=0

**Comment by neonstalwart** [comment]
is this fixed with #181?  even though you're referencing a commit after that fix was applied, dist doesn't include that fix.

**Comment by CRogers** [comment]
Oh awesome! Probably should have tried the latest version. Would it be possible to make point release with this fix (and possibly the other changes since 1.3.0) in it?

**Comment by neonstalwart** [comment]
cc @Matt-Esch - can you do a release?

**Comment by CRogers** [comment]
This doesn't appear to be fixed. I ran `npm dist` on top of latest master (3ea4f0e - I made a gist of it: https://gist.github.com/CRogers/b5328187a3223e6defc3) and it still fails in a different but equally bad way. See http://jsfiddle.net/CARogers/88d5dqj3/ (it has an updated external resource) and:

Frame 1 - 5x2 | Frame 2 - 5x3 | Frame 3 - 5x2
--------- | ------------- | ------------
![screen shot 2015-02-18 at 17 25 07](https://cloud.githubusercontent.com/assets/397795/6252556/27d11674-b793-11e4-9248-a13257eae37d.png) | ![screen shot 2015-02-18 at 17 25 17](https://cloud.githubusercontent.com/assets/397795/6252564/3196e5f8-b793-11e4-8336-140e9899db42.png) | ![screen shot 2015-02-19 at 14 57 39](https://cloud.githubusercontent.com/assets/397795/6268878/baa9f22c-b847-11e4-8454-a3bc462b74c5.png)

I've also updated the more complicated example: http://jsfiddle.net/CARogers/tsjLprv0/1/

**Comment by neonstalwart** [comment]
@CRogers :disappointed: i'm sorry  about that.  the first part of fixing this is to get a reduced test case like https://github.com/Matt-Esch/virtual-dom/commit/ee8d4a25724fd874aa7907898748d2935b2436f8.  my plate is kind of full right now and i'll eventually get to this if someone doesn't do it before me but **if** you have any time to come up with a PR of a failing test case that will help get this done sooner.

**Comment by CRogers** [comment]
Cool - I'll have a go at making a failing test case.

**Comment by CRogers** [comment]
Is there a getting started dev guide anywhere?

**Comment by neonstalwart** [comment]
good question... i don't think so but here's a quick start for you.

* clone the repo
* `npm install`
* `npm run browser` - will start a server that serves the tests to the browser.  i write a failing test case and often use `test.only( ... )` to isolate that one test and from there, i use the developer tools to debug the issue.  write some code, try again, and again, and again...
* when i think i've fixed the bug, i make sure to change `test.only( ... )` back to `test( ... )` and run `npm test` to double-check that everything else is still working.

**Comment by CRogers** [comment]
Thanks for that! Saved me loads of time. I've managed to make one test case (this time using smaller grids, which is nice) at https://github.com/CRogers/virtual-dom/commits/feature/191-keyed-correctness-tests. I'll try to make more if I can make any other small ones.

**Comment by CRogers** [comment]
I tried debugging it myself, it seems the patch produced for the second call of `diff` is producing `REMOVE` patches for the right elements, but I can't work out the numbering/indexing system used for the `ORDER` patch, especially the `reverse` section.

**Comment by neonstalwart** [comment]
i'm quite confident that the patches will be correct.  the likely candidate for the cause of this bug is (another) off-by-one error in https://github.com/Matt-Esch/virtual-dom/issues/104#issuecomment-73732749

**Comment by neonstalwart** [comment]
to explain what you're looking at in a patch, the hash describes how to move nodes:

```js
{
  0: 4
}
```

means move previous node 4 to position 0

`reverse` is the same thing in reverse

```js
{
  4: 0
}
```

this helps with optimizing the reordering of nodes.  working from lowest index, to highest, we can figure out if a node currently at a lower index will be moved later and so we can leave it in place for now and maybe even won't need to move it if we put enough other nodes before it.

**Comment by CRogers** [comment]
I think I've found where it's going wrong - it's the first `patch` call. The patch produced by `diff` seems correct, as on paper after the diff it should end up as:

0-0
1-0
0-1
1-1
0-2
1-2

(assuming that `INSERT`s insert at the end and the `reverse` property on `ORDER` is a mapping from old positions to new ones)

Whereas `rootNode` ends up like this after `patch` is called:

0-0
1-0
0-1
1-1
**1-2**
**0-2**

**Comment by neonstalwart** [comment]
yeah, so you want to focus your attention at https://github.com/Matt-Esch/virtual-dom/blob/3ea4f0e6afe6ff01c056513d3b5743c540b45419/vdom/patch-op.js#L138-L174 which is where we take the diff and apply it to the nodes.  there must be an off-by-one error in there (again :disappointed:)

**Comment by CRogers** [comment]
I'm now trying to follow along on paper but it's quite complicated. I going to have to give up for the day soon anyhow.

**Comment by neonstalwart** [comment]
no problem, the test case helps me a lot and i'm glad to have someone new that at least takes an interest in that code - i definitely use paper when working on that section.  it's simple enough to get that code right without optimizations but the optimizations are what make it more difficult.

**Comment by CRogers** [comment]
Mmmm, I would like to get involved in the project (primarily because it makes the haskell-on-the-web story a lot better) but I'm also trying to apply this at work to get rid of some mutable-spaghetti render code.

I've also just pushed up a simplified version of the test case (no more grids, only one diff/patch). I'm going to clean it up a bit more now.

**Comment by neonstalwart** [comment]
awesome... if you use irc at all, join us at #virtualdom.  i'd love to do whatever i can to help anyone with an interest.
